baseURL = 'https://dp9166.github.io/'
languageCode = 'zh-Hans'
title = 'My Blog'
theme = 'moments'

[params]
    title = "念"
    signature = "时光轻浅处, 一步一安然"
    cover = "../images/cover.png"
    author = 'Duanpei'
    

    name = "Default User"
    avatar = "../images/avatar.png"
